Add brief explanation of private channel usage.
WeAllJS/wheelie-slack-app pull request #15
Opened 2017-01-19 01:59 UTC by ayust

2017-01-19 09:07 UTC, Charlotteis commented on lib/commands/list-private.js
> +    text: `These channels are private to disallow previewing (view wihtout join). Available private channels: `,
hey! little spelling mistake here,

`wihtout` should be `without` :)

2017-01-19 18:47 UTC, aredridel requested changes
I like the change, but it does have a typo!

2017-01-19 19:56 UTC, ayust commented on lib/commands/list-private.js
> +    text: `These channels are private to disallow previewing (view wihtout join). Available private channels: `,
fixed

2017-01-24 17:23 UTC, Charlotteis commented
Looks good to me! Thank you @ayust :)

2017-01-24 17:23 UTC, merged